/* Generated By:JavaCC: Do not edit this line. JaggerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JaggerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int THEN = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int LET = 13;
  /** RegularExpression Id. */
  int IN = 14;
  /** RegularExpression Id. */
  int END = 15;
  /** RegularExpression Id. */
  int VAR = 16;
  /** RegularExpression Id. */
  int VARNAME = 17;
  /** RegularExpression Id. */
  int ASSIGN = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\",\"",
    "<NUMBER>",
    "<STRING>",
    "<DIGIT>",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"print\"",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\"var\"",
    "<VARNAME>",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
